FROM node:16-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY generate-nginx-conf.sh /
RUN chmod +x /generate-nginx-conf.sh
EXPOSE 80
CMD ["/generate-nginx-conf.sh"]
